// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaA1e8yVEaVjqdPBM9UPCot616silNrTo',
    appId: '1:121014473008:web:1b21ca12ba759d168438f5',
    messagingSenderId: '121014473008',
    projectId: 'whatsapp-clone-dbf0d',
    authDomain: 'whatsapp-clone-dbf0d.firebaseapp.com',
    storageBucket: 'whatsapp-clone-dbf0d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX8k6NBxF464z3hlblfexUfypzh6nhoD8',
    appId: '1:121014473008:android:401411e334684d3e8438f5',
    messagingSenderId: '121014473008',
    projectId: 'whatsapp-clone-dbf0d',
    storageBucket: 'whatsapp-clone-dbf0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHI7l3EcLDxh2oF-w3fVu-cANySvP5IVo',
    appId: '1:121014473008:ios:28aa7473df6969bd8438f5',
    messagingSenderId: '121014473008',
    projectId: 'whatsapp-clone-dbf0d',
    storageBucket: 'whatsapp-clone-dbf0d.appspot.com',
    iosBundleId: 'com.example.whatsappclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHI7l3EcLDxh2oF-w3fVu-cANySvP5IVo',
    appId: '1:121014473008:ios:28aa7473df6969bd8438f5',
    messagingSenderId: '121014473008',
    projectId: 'whatsapp-clone-dbf0d',
    storageBucket: 'whatsapp-clone-dbf0d.appspot.com',
    iosBundleId: 'com.example.whatsappclone',
  );
}
